build:
  maxIssues: 0

complexity:
  active: true
  ComplexCondition:
    threshold: 4
  CyclomaticComplexMethod:
    threshold: 15
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 6
    constructorThreshold: 6
  NestedBlockDepth:
    threshold: 4
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20

style:
  active: true
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  WildcardImport:
    active: false
  MaxLineLength:
    maxLineLength: 120

naming:
  active: true
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
  VariableNaming:
    variablePattern: '[a-z][a-zA-Z0-9]*'

performance:
  active: true

exceptions:
  active: true

potential-bugs:
  active: true